In [1]:
import numpy as np

In [2]:
np.array

<function numpy.core.multiarray.array>

In [3]:
np.array(object,dtype=None,copy=True,order=None,subok=False,ndmin=0)

array(<class 'object'>, dtype=object)

In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
import numpy as np
a=np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [7]:
import numpy as np
a=np.array([1,2,3],dtype=complex)
print(a)

[ 1.+0.j  2.+0.j  3.+0.j]


In [8]:
#NumPy Datatype

In [9]:
import numpy as np
dt=np.dtype(np.int32)
print(dt)

int32


In [10]:
dt=np.dtype('i4')
print(dt)

int32


In [11]:
dt=np.dtype('>i4')
print(dt)

>i4


In [12]:
dt=np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [13]:
import numpy as np
dt=np.dtype([('age',np.int8)])
a=np.array([(10,),(20,),(30,)],dtype=dt)
print(a)

[(10,) (20,) (30,)]


In [14]:
import numpy as np
dt=np.dtype([('age',np.int8)])
a=np.array([(10,),(20,),(30,)],dtype=dt)
print(a['age'])

[10 20 30]


In [15]:
import numpy as np
students=np.dtype([('name','S20'),('age','i1'),('marks','<f4')])
print(students)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [38]:
students=np.dtype([('name','S20'),('age','i1'),('makrs','f4')])
a=np.array([('abc',21,50),('xyz',18,75)],dtype=students)
print(a)

[(b'abc', 21,  50.) (b'xyz', 18,  75.)]


In [17]:
#NumPy Array Attribute

In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [19]:
#resize ndarray
import numpy as np
a=np.array([[[[[1,2,3],[4,5,6]]]]])
print(a.ndim)
a.shape=(3,2)
print(a)

5
[[1 2]
 [3 4]
 [5 6]]


In [20]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [22]:
#one dimensional array
import numpy as np
a=a.reshape(2,6,2)
print(a)
print(a.ndim)

#now reshape it
b=a.reshape(2,4,3)
print(b)
#b has three dimension

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]]]
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [23]:
#return length of each element of array in bytes
import numpy as np
x=np.array([1,2,3,4,5,6],dtype=np.int8)
print(x.itemsize)

1


In [24]:
#return length of each element of array in bytes
import numpy as np
x=np.array([1,2,3,4,5,6],dtype=np.float32)
print(x.itemsize)

4


In [25]:
#Shows current values of flags
import numpy as np
x=np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [26]:
#Array Creation Routines

In [27]:
import numpy as np
x=np.empty([3,2],dtype=np.int)
print(x)

[[1065353216 1073741824]
 [1077936128 1082130432]
 [1084227584 1086324736]]


In [28]:
import numpy as np
x=np.zeros(5)
print(x)
x=np.zeros((5,),dtype=np.int)
print(x)

[ 0.  0.  0.  0.  0.]
[0 0 0 0 0]


In [29]:
import numpy as np
x=np.zeros((2,2),dtype=[('x','i4'),('y','i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [30]:
import numpy as np
x=np.ones(5)
print(x)
x=np.ones([2,2],dtype=int)
print(x)

[ 1.  1.  1.  1.  1.]
[[1 1]
 [1 1]]


In [31]:
#Array From Existing Data

In [32]:
#converting list into ndarray
import numpy as np
x=[1,2,3]
a=np.asarray(x)
print(a)

[1 2 3]


In [33]:
#dtype is set
import numpy as np
x=[1,2,3]
a=np.asarray(x,dtype=float)
print(a)

[ 1.  2.  3.]


In [34]:
#ndarray from tuple
x=(1,2,3)
a=np.asarray(x)
print(a)

[1 2 3]


In [35]:
#ndarray from list of tuples
import numpy as np
x=[(1,2,3),(4,5)]
a=np.asarray(x)
print(a)

[(1, 2, 3) (4, 5)]


In [36]:
print(a.ndim)

1
